# Site settings
title: From Architect to Full Stack Developer
header-img: img/home-bg.png
email: buchheimt@yahoo.com
copyright_name: buchheimt
description: > # this means to ignore newlines until "baseurl:"
  Design is Design... Right?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  buchheimt
learn_profile: buchheimt
email_username: buchheimt@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
